{
 "title": "Simulación de Tráfico Distribuido",
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehículos por Nodo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "vehiculos_nodo", "legendFormat": "{{zona}}" }
   ]
  },
  {
   "title": "Nodos HEALTHY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nodos_healthy" }
   ]
  },
  {
   "title": "Nodos OVERLOADED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "nodos_overloaded" }
   ]
  },
  {
   "title": "Nodos UNHEALTHY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "nodos_unhealthy" }
   ]
  },
  {
   "title": "Heart-beats por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(heartbeats_total[1m])", "legendFormat": "HB/s" }
   ]
  }
 ]
}