global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "coordinador"
    static_configs:
      - targets: ["host.docker.internal:8001"]   # métrica /metrics del coordinador

  - job_name: "zonas"
    static_configs:
      - targets:
          - "host.docker.internal:9200"         # zona_distribuida
          # añade más nodos si abres otros runners → 9201, 9202, …
